c = physconst('lightspeed');
R0 = [100 1e3 10e3];
freq = (1:1000).'*1e9;
apathloss = fspl(R0,c./freq);
loglog(freq/1e9,apathloss);
grid on;
ylim([90 200]);
legend('Zasięg: 100 m', 'Zasięg: 1 km', 'Zasięg: 10 km','Location','northwest');
xlabel('Częstotliwość (GHz)');
ylabel('Straty na ścieżce (dB)');
title('Straty na ścieżce w wolnej przestrzeni');